base:
  use_cuda: True

data:
  dataset_folder: /content/drive/MyDrive/DS310
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv

tokenizer:
  padding: max_length
  max_length: 64
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  type: pretrained #có 3 loại, pretrained,count_vector,tf_idf,nếu ko xài ptretrain cnn phải chỉnh kernel_size bằng 1
  text_encoder: vinai/phobert-base
  freeze: True
  d_features: 768
  d_model: 512
  dropout: 0.2

model:
  type_model: bert_cnn
  name: sentiment_analysis  # Custom name for the model
  intermediate_dims: 512
  dropout: 0.2
train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 0.01
  weight_decay: 0.0
  warmup_ratio: 0.0
  warmup_steps: 0
  metric_for_best_model: f1
  train_batch_size: 256
  eval_batch_size: 256
inference:
  batch_size: 512